// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA78eH6hueh6oig0T6dpFZud7awLq8dO7Y',
    appId: '1:425264795928:web:9008c9b12f7a7df49b0e6d',
    messagingSenderId: '425264795928',
    projectId: 'anggaa-projectotp',
    authDomain: 'anggaa-projectotp.firebaseapp.com',
    databaseURL: 'https://anggaa-projectotp-default-rtdb.firebaseio.com',
    storageBucket: 'anggaa-projectotp.appspot.com',
    measurementId: 'G-SQCLMJF445',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2BqS1jvieRu3AjZz3c0-6oK8V3rTa5Q',
    appId: '1:425264795928:android:a64a7f7d335641499b0e6d',
    messagingSenderId: '425264795928',
    projectId: 'anggaa-projectotp',
    databaseURL: 'https://anggaa-projectotp-default-rtdb.firebaseio.com',
    storageBucket: 'anggaa-projectotp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJR2wr_skWk2XD16JoOjpHvZtk-zCLBDc',
    appId: '1:425264795928:ios:1f82db276300a2439b0e6d',
    messagingSenderId: '425264795928',
    projectId: 'anggaa-projectotp',
    databaseURL: 'https://anggaa-projectotp-default-rtdb.firebaseio.com',
    storageBucket: 'anggaa-projectotp.appspot.com',
    androidClientId: '425264795928-c69lq7j9gliuis58a8t2ejhhq93hctog.apps.googleusercontent.com',
    iosClientId: '425264795928-jeb4jmf4kc8427f38u6985qo8e9a21f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFirebase',
  );
}
